# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-20 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageChooser',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_lang_chooser_languagechooser', serialize=False, to='cms.CMSPlugin')),
                ('template', models.CharField(blank=True, choices=[('raw', 'Raw language marker'), ('native', 'Native language marker'), ('current', 'Current language marker'), ('short', 'Short language marker')], max_length=10)),
                ('template_other', models.CharField(blank=True, max_length=200)),
                ('i18n_mode', models.CharField(blank=True, choices=[('raw', 'Raw language marker'), ('native', 'Native language marker'), ('current', 'Current language marker'), ('short', 'Short language marker')], max_length=10)),
                ('i18n_mode_other', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
